
INSERT INTO CURSO (CURSO_ID, CURSO_NOME, CURSO_VAGAS, CURSO_REFERENCIA, CURSO_EXTENSAO, CURSO_FLAG) VALUES
(1, 'Administração', 100, 'vestibular', '0', '1'),
(2, 'Análise de Sistemas', 40, 'vestibular', '0', '0'),
(3, 'Ciências Econômicas', 40, 'vestibular', '0', '0'),
(4, 'Direito', 146, 'vestibular', '0', '1'),
(5, 'Enfermagem', 64, 'vestibular', '0', '1'),
(6, 'História', 30, 'vestibular', '0', '1'),
(7, 'Letras', 40, 'vestibular', '0', '1'),
(8, 'Matemática', 40, 'vestibular', '0', '0'),
(9, 'Medicina', 80, 'vestibularmedicina', '0', '1'),
(10, 'Medicina Veterinária', 40, 'vestibular', '0', '1'),
(11, 'Odontologia', 70, 'vestibular', '0', '1'),
(12, 'Pedagogia', 60, 'vestibular', '0', '1'),
(13, 'Recursos Humanos', 40, 'vestibular', '0', '1'),
(14, 'Internato Residência Médica', 9, 'residenciamedica', '0', '0'),
(15, 'Internato RM - Medicina da Familia e Comunidade', 5, 'residenciamedica', '0', '0'),
(16, 'Recurso - Residencia Médica', 0, 'residenciamedica', '0', '0'),
(17, 'Especialização Pecuária Leiteira', 40, 'pospecuarialeiteira', '0', '0'),
(18, 'Téc. em Informática', 0, 'pronatec', '0', '0'),
(19, 'Téc. em Informática para Internet', 0, 'pronatec', '0', '0'),
(20, 'Téc. em Saúde Bucal', 0, 'pronatec', '0', '0'),
(21, 'Téc. em Prótese Dentária', 0, 'pronatec', '0', '0'),
(22, 'Téc. em Agropecuária', 0, 'pronatec', '0', '0'),
(23, 'Téc. em Zootecnia', 0, 'pronatec', '0', '0'),
(24, 'LIGA ACADÊMICA DE ATENÇÃO BASICA A SAUDE', 60, 'ligaacademica', '1', '0'),
(25, 'LIGA ACADÊMICA DE PNEUMOLOGIA', 60, 'ligaacademica', '1', '0'),
(26, 'LIGA ACADÊMICA DE NEUROLOGIA', 80, 'ligaacademica', '1', '0'),
(27, 'LIGA ACADÊMICA DE SEMIOLOGIA', 60, 'ligaacademica', '1', '0'),
(28, 'LIGA ACADÊMICA DE GASTROENTEROLOGIA', 60, 'ligaacademica', '1', '0'),
(29, 'LIGA ACADÊMICA DE EMERGÊNCIA', 60, 'ligaacademica', '1', '0'),
(30, 'LIGA ACADÊMICA DE UROLOGIA', 60, 'ligaacademica', '1', '0'),
(31, 'LIGA ACADÊMICA DE GINECOLOGIA', 200, 'ligaacademica', '1', '0'),
(32, 'LIGA ACADÊMICA DE CARDIOLOGIA', 60, 'ligaacademica', '1', '0'),
(33, 'LIGA ACADÊMICA DE PEDIATRIA', 60, 'ligaacademica', '1', '0'),
(34, 'Especialização em Produção de Bovinos', 25, 'posbovino', '0', '0'),
(35, 'Introdução ao Estudo do Processo Penal', 0, 'cursoprocessopenal', '1', '0');